Repository dedis/popstellar, pull requests merged in 2020-10, with the labels that each got.

#6 Home UI
  README.md
  app/build.gradle
  app/src/androidTest/java/com/github/dedis/student20_pop/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/github/dedis/student20_pop/MainActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/dedis/student20_pop/MainActivity.java
  app/src/main/java/com/github/dedis/student20_pop/ui/ConnectFragment.java
  app/src/main/java/com/github/dedis/student20_pop/ui/HomeFragment.java
  app/src/main/java/com/github/dedis/student20_pop/ui/LaunchFragment.java
  app/src/main/java/com/github/dedis/student20_pop/ui/package-info.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_connect.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_launch.xml
  app/src/main/res/layout/tab_connect_launch.xml
  app/src/main/res/layout/tab_home.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/dedis/student20_pop/ExampleUnitTest.java
Labels: enhancement

#9 Strings moved to dedicated file
  PopApp/Components/Attendee.js
  PopApp/Components/Connect.js
  PopApp/Components/ConnectConfirm.js
  PopApp/Components/ConnectConnecting.js
  PopApp/Components/ConnectScanning.js
  PopApp/Components/ConnectUnapprove.js
  PopApp/Components/Home.js
  PopApp/Components/Launch.js
  PopApp/Components/Organization.js
  PopApp/Navigation/ConnectNavigation.js
  PopApp/Navigation/Navigation.js
  PopApp/app.json
  PopApp/res/assets/favicon.png
  PopApp/res/assets/icon.png
  PopApp/res/assets/splash.png
  PopApp/res/img/ic_camera.png
  PopApp/res/strings.js
  README.md
Labels: enhancement

#10 Launch UI
  app/src/androidTest/java/com/github/dedis/student20_pop/MainActivityTest.java
  app/src/main/java/com/github/dedis/student20_pop/MainActivity.java
  app/src/main/java/com/github/dedis/student20_pop/model/Lao.java
  app/src/main/java/com/github/dedis/student20_pop/model/package-info.java
  app/src/main/java/com/github/dedis/student20_pop/ui/HomeFragment.java
  app/src/main/res/layout/fragment_launch.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/dedis/student20_pop/LaoTest.java
Labels: enhancement

#18 Basic web app
  PopApp/.gitignore
  PopApp/App.js
  PopApp/Components/Attendee.js
  PopApp/Components/CameraButton.js
  PopApp/Components/ConnectConfirm.js
  PopApp/Components/ConnectConnecting.js
  PopApp/Components/ConnectScanning.js
  PopApp/Components/ConnectUnapprove.js
  PopApp/Components/Home.js
  PopApp/Components/Launch.js
  PopApp/Components/Organization.js
  PopApp/Navigation/ConnectNavigation.js
  PopApp/Navigation/Navigation.js
  PopApp/package-lock.json
  PopApp/res/strings.js
  README.md
Labels: bug

#33 Json communication protocol definition + JsonMessageParser
  README.md
  build.sbt
  src/main/scala/json/JsonCommunicationProtocol.scala
  src/main/scala/json/JsonMessageParser.scala
  src/main/scala/json/JsonMessageTypes.scala
  src/main/scala/json/JsonMessages.scala
  src/test/scala/json/JsonMessageParserTest.scala
Labels: documentation, enhancement

#34 Coding convention
  PopApp/.eslintrc
  PopApp/Components/Attendee.js
  PopApp/Components/CameraButton.js
  PopApp/Components/ConnectConfirm.js
  PopApp/Components/ConnectConnecting.js
  PopApp/Components/ConnectScanning.js
  PopApp/Components/ConnectUnapprove.js
  PopApp/Components/Home.js
  PopApp/Components/Launch.js
  PopApp/Components/Organization.js
  PopApp/Navigation/ConnectNavigation.js
  PopApp/Navigation/Navigation.js
  PopApp/Styles/buttons.js
  PopApp/Styles/colors.js
  PopApp/Styles/index.js
  PopApp/Styles/spacing.js
  PopApp/Styles/typography.js
  PopApp/Styles/views.js
  PopApp/package-lock.json
  PopApp/package.json
  PopApp/res/strings.js
  README.md
Labels: documentation

#43 Work be2 sebastien
  build.sbt
  src/main/scala/HelloWorld.scala
  src/main/scala/ch/epfl/pop/Server.scala
  src/main/scala/ch/epfl/pop/json/JsonCommunicationProtocol.scala
  src/main/scala/ch/epfl/pop/json/JsonMessageParser.scala
  src/main/scala/ch/epfl/pop/json/JsonMessageTypes.scala
  src/main/scala/ch/epfl/pop/json/JsonMessages.scala
  src/main/scala/ch/epfl/pop/pubsub/ChannelActor.scala
  src/main/scala/ch/epfl/pop/pubsub/PublishSubscribe.scala
  src/test/scala/json/JsonMessageParserTest.scala
  src/test/scala/pubsub/PubSubTest.scala
Labels: enhancement
