Repository dedis/popstellar, pull requests merged in 2023-10, with the labels that each got.

#1690 Fe2 CI got stuck
  fe2-android/app/src/test/unit/java/com/github/dedis/popstellar/repository/DigitalCashRepositoryTest.java
  fe2-android/app/src/test/unit/java/com/github/dedis/popstellar/repository/ElectionRepositoryTest.java
  fe2-android/app/src/test/unit/java/com/github/dedis/popstellar/repository/MeetingRepositoryTest.java
  fe2-android/app/src/test/unit/java/com/github/dedis/popstellar/repository/SocialMediaRepositoryTest.java
  fe2-android/app/src/test/unit/java/com/github/dedis/popstellar/repository/WitnessingRepositoryTest.java
Labels: fe2-android, bug-fix

#1695 Added PR Stat github action
  .github/workflows/stats.yml
Labels: ci/cd

#1704 Solve format deprecation in Popcha CI
  .github/workflows/ci.yaml
Labels: bug-fix, ci/cd, popcha

#1701 Constants for feature paths
  tests/karate/src/test/java/be/features/LAO/create.feature
  tests/karate/src/test/java/be/features/LAO/update.feature
  tests/karate/src/test/java/be/features/decentralizedCom/getMessagesById.feature
  tests/karate/src/test/java/be/features/decentralizedCom/heartbeat.feature
  tests/karate/src/test/java/be/features/digitalCash/transaction.feature
  tests/karate/src/test/java/be/features/election/castVote.feature
  tests/karate/src/test/java/be/features/election/electionEnd.feature
  tests/karate/src/test/java/be/features/election/electionOpen.feature
  tests/karate/src/test/java/be/features/election/electionSetup.feature
  tests/karate/src/test/java/be/features/rollCall/closeRollCall.feature
  tests/karate/src/test/java/be/features/rollCall/createRollCall.feature
  tests/karate/src/test/java/be/features/rollCall/openRollCall.feature
  tests/karate/src/test/java/be/features/utils/constants.feature
  tests/karate/src/test/java/be/features/utils/simpleScenarios.feature
Labels: prod-ready
